# Common env variables
bu: set
environment: dev
projectname: helloapp
applicationrole: cicdaks
replicaCount: 1
namespace: ns-set-dev-aks-cicd
managedIdentityClientId: f7366529-31c6-4ae6-b831-10cca3083b7c
pullPolicy: IfNotPresent
containerPort: 80
nodeSelector: {}
tolerations: []
affinity: {}

# POD Resource limits
resources:
  limits:
    cpu: 850m
    memory: 2Gi
  requests:
    cpu: 150m
    memory: 1Gi

# Service
service:
  port: 80

# Network Policy North-South:
inboundPolicyNorthSouth:
  enabled: false

# Ingress
ingress:
  enabled: false


# App Configuration
appconfig:
  enabled: false


# Environment variables
env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
  - name: ASPNETCORE_HTTP_PORTS
    value: 80